# Generated by Django 5.1.3 on 2024-11-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocupada', models.BooleanField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planta')),
            ],
        ),
        migrations.CreateModel(
            name='PlazaLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField()),
                ('plaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plaza')),
            ],
        ),
    ]
