# Generated by Django 5.1.3 on 2024-11-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parking_latitude_parking_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='accesible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
